### ISSUE TITLE
Unexpected exception while handling result in ResponseFuture:

### ISSUE THREAD

**Issue by Riki-1mg** [CharAct3/aiocqlengine#9]
Hi Team, 

I am using using Aiocqlengine for long time, the issue i recently faced when we move to kubernitics 
is **Unexpected exception while handling result in ResponseFuture:** for every query we execute ? can u please tell me why ?

Error in 

aiocqlengine/session.py in _asyncio_result at line 16

**Comment by CharAct3** [comment]
Hi, maybe it's caused by the `0.3.0` update. I removed the `aiocassandra` dependency due to it's unmaintained.

And I noticed there is a bug if you didn't set loop in `aiosession_for_cqlengine(session, loop)`. I fixed it in `0.3.1`.

If updating to the `0.3.1` version doesn't fix this issue, please give me more information about the issue or try to downgrade to `aiocqlengine==0.2.0` as temporary solution.

**Comment by Riki-1mg** [comment]
Thanks for Your Revert, I am downgrading the version to 0.2.0. Whenever you update I will change it

**Comment by CharAct3** [comment]
Hi Riki, the `0.3.1` version has been published. 

I can't reproduce this issue in my dev environment or unittests. If the new version doesn't fix your issue, please give me more information about it. Thanks.

**Comment by Riki-1mg** [comment]
Hi Team, 
I update the version to 0.3.1 and its working fine. Thanks
